return {
    filetypes = {
        'astro',
        'eruby',
        'html',
        'xhtml',
        'smarty',
        'htmldjango',
        'javascriptreact',
        'typescriptreact',
        'css',
        'less',
        'sass',
        'scss',
        'svelte',
        'pug',
        'vue',
        'blade',
    },
}
