return {
    'tpope/vim-sensible',
    'nvim-treesitter/nvim-treesitter-refactor',
    'm-demare/hlargs.nvim',
    'windwp/nvim-spectre',
    { 'nacro90/numb.nvim', config = true },
    { 'tris203/precognition.nvim', config = true },
    'HiPhish/rainbow-delimiters.nvim',
    { 'lukas-reineke/virt-column.nvim', config = true },
    'gpanders/editorconfig.nvim',
    'romainl/vim-cool',
    'itchyny/calendar.vim',
    'ludovicchabant/vim-lawrencium',
    'jghauser/mkdir.nvim',
    'tpope/vim-fugitive',
    'JoosepAlviste/nvim-ts-context-commentstring',
    'folke/todo-comments.nvim',
    { 'numtostr/BufOnly.nvim', cmd = 'BufOnly' },
    { 'lukas-reineke/indent-blankline.nvim', main = 'ibl', config = true },
    {
        'vhyrro/luarocks.nvim',
        priority = 1000,
        opts = {
            rocks = { 'lua-curl', 'nvim-nio', 'mimetypes', 'xml2lua' },
        },
    },
    'niuiic/translate.nvim',
    'MeanderingProgrammer/render-markdown.nvim',
    { 'chrisgrieser/nvim-puppeteer', lazy = false },
    -- { 'mluders/comfy-line-numbers.nvim', config = true },
    { 'nvim-lua/plenary.nvim', branch = 'master', lazy = true },
    { 'kevinhwang91/promise-async', lazy = true },
    { 'nvim-tree/nvim-web-devicons', lazy = true },
    { 'niuiic/core.nvim', lazy = true },
    {
        'heilgar/nvim-http-client',
        event = 'VeryLazy',
        ft = { 'http', 'rest' },
        opts = {},
    },
    {
        'soulis-1256/eagle.nvim',
        opts = {
            border = 'rounded',
            keyboard_mode = true,
            mouse_mode = false,
        },
    },
}
