return {
    sort_by = 'case_sensitive',
    view = {
        adaptive_size = true,
        mappings = {
            list = {
                { key = { '<CR>', 'o', '<2-LeftMouse>', 'l' }, action = 'edit' },
                { key = '<C-e>', action = 'edit_in_place' },
                { key = 'O', action = 'edit_no_picker' },
                { key = { '<C-]>', '<2-RightMouse>' }, action = 'cd' },
                { key = 'P', action = 'parent_node' },
                { key = 'h', action = 'close_node' },
                { key = '<Tab>', action = 'preview' },
                { key = 'I', action = 'toggle_git_ignored' },
                { key = 'H', action = 'toggle_dotfiles' },
                { key = 'R', action = 'refresh' },
                { key = 'a', action = 'create' },
                { key = 'd', action = 'remove' },
                { key = 'D', action = 'trash' },
                { key = 'r', action = 'rename' },
                { key = '<C-r>', action = 'full_rename' },
                { key = 'x', action = 'cut' },
                { key = 'c', action = 'copy' },
                { key = 'p', action = 'paste' },
                { key = 'y', action = 'copy_name' },
                { key = 'Y', action = 'copy_path' },
                { key = 'gy', action = 'copy_absolute_path' },
                { key = '<BS>', action = 'dir_up' },
                { key = 'q', action = 'close' },
                { key = 'W', action = 'collapse_all' },
                { key = 'E', action = 'expand_all' },
                { key = 'S', action = 'search_node' },
                { key = '<C-k>', action = 'toggle_file_info' },
                { key = '?', action = 'toggle_help' },
            },
        },
    },
    renderer = {
        group_empty = true,
    },
    filters = {
        dotfiles = false,
    },
}
