#!/usr/bin/env bash

echo "# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {
    listen 80;
    listen [::]:80;

    server_name $1.localhost;

    location / {
        proxy_pass http://127.0.0.1:$2;
        include proxy_params;
    }
}" | sudo tee /etc/nginx/sites-available/$1.conf
sudo ln -s /etc/nginx/sites-available/$1.conf /etc/nginx/sites-enabled/$1.conf
sudo systemctl restart nginx
